package com.example.aws.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@DynamoDBTable(tableName = "order")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Order {

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  private String id;
  @DynamoDBAttribute
  private String orderDate;
  @DynamoDBAttribute
  private String orderName;
  @DynamoDBAttribute
  private Boolean orderStatus;
  @DynamoDBAttribute
  private Customer customer;


}
